### ISSUE TITLE
Ability to disable Autocomplete-input

### ISSUE THREAD

**Issue by toddmetheny** [l-urence/react-native-autocomplete-input#10]
There is probably already a way to do this but I couldn't find it in the documentation. I want to disable the autocomplete while the data loads. I also want to limit what can be submitted. Tried simply adding `disabled={this.state.loading}` but that didn't work.

 How would I do this using react-native-autocomplete-input? Thanks in advance.

**Comment by l-urence** [comment]
There is no such thing as `disabled={this.state.loading}` implemented right now. If you want to disable the `TextInput` try to pass the `editable={false}` to the autocomplete component.

**Comment by l-urence** [comment]
Closing this issue for now. Feel free to reopen if this needs more discussion.
