### ISSUE TITLE
 TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by dineshsuvendiran** [l-urence/react-native-autocomplete-input#104]
I get  this error when i try to mock, and my test file looks like this

`import React from 'react';`
`jest.mock('react-native-autocomplete-input', () => 'Autocomplete')`
`import UserSearch from '../components/UserSearch';`
`import renderer from 'react-test-renderer';`
`describe('<UserSearch/>', ()=>{`
   ` it('renders correctly', () => {`
       ` const tree = renderer`
         ` .create(<UserSearch />)`
          `.toJSON();`
      ` expect(tree).toMatchSnapshot();`
     ` }); `  
`})`
The UserSearch compnent using Autocomplete library. And i get the error from where the library getting imported `import Autocomplete from 'react-native-autocomplete-input';`

**Comment by massivespace** [comment]
Same here.  I ended up editing the react-native-autocomplete-input/index.js file and replacing ListView.propTypes.style with ViewPropsType.style, and it fixed the crash (although I don't know if that is a proper fix, probably not).  The ListView is deprecated anyway, so honestly should be replaced with a FlatList according to react native docs.

**Comment by ViktorAksionov** [comment]
After migration to react-native 0.57 I  got issue with this also. Solution - remove this line `listStyle: ListView.propTypes.style,`

**Comment by zedtux** [comment]
Same as @ViktorAksionov.

**Comment by l-urence** [comment]
Should be fixed by #106
