### ISSUE TITLE
2 on the same page opens both suggestions boxes

### ISSUE THREAD

**Issue by anotherstarburst** [l-urence/react-native-autocomplete-input#14]
If I put two autocomplete inputs on the same page, starting to type in one opens the second suggestion box also.

**Comment by l-urence** [comment]
You may pass the same data from the first autocomplete to the second one as well?

**Comment by sergiocloud** [comment]
Hi! Same issue here. I'm using two different data and I confirm one is empty when the other has items. I think it may be a problem with the refs you are using.

**Comment by l-urence** [comment]
Yes, seems to be something when the component is rerendered. I don't think it's because of the refs they are not used internally.

**Comment by l-urence** [comment]
@sergiocloud I simplified the logic to open the suggestion list this should fix the issue. The changes are published in [3.0.0-rc.1](https://github.com/l-urence/react-native-autocomplete-input/releases/tag/3.0.0-rc.1).

**Comment by sergiocloud** [comment]
Problem fixed with 3.0.0-rc.1, thanks!

**Comment by ahtisham09** [comment]
@sergiocloud  how did you solve this problem can you please tell me
