### ISSUE TITLE
How to float ontop of content beneath?

### ISSUE THREAD

**Issue by kevinsimper** [l-urence/react-native-autocomplete-input#15]
Right now my app looks like this and I can't seem to understand how to make it float ontop like yours demo!

Is it possible? Btw, thanks for the library!

![image](https://cloud.githubusercontent.com/assets/1126497/17840931/c46f9056-6812-11e6-8c83-e0987913426a.png)

**Comment by kevinsimper** [comment]
I got it to look like this with position relative and absolute:
![image](https://cloud.githubusercontent.com/assets/1126497/17841211/9b1e35e6-6816-11e6-954a-045ea527a302.png)

**Comment by l-urence** [comment]
If the relative position solution works out for you I will close this issue.

**Comment by kevinsimper** [comment]
@l-urence Yeah, but the gif in the readme looks like it is floating, is it? How did you do it?

**Comment by l-urence** [comment]
No, the example autocomplete container position is [absolute](https://github.com/l-urence/react-native-autocomplete-input/blob/master/example/Example.js#L96).

**Comment by kevinsimper** [comment]
@l-urence Would it be an idea to put that into the module? Because it does not really make sense without :)

**Comment by l-urence** [comment]
@kevinsimper Actually this is true! But right now I didn't figure out how to to this in a good way (lack of time). The absolute position seems to be more some kind of "hack" to put the suggestion list on top of other elements. For that reason I excluded the positioning to the example. An optimal solution would be to add the autocomplete like the `<TextInput />` to a component and the suggestion list will appear over other elements. Without strange behaviours which could happen if you set it to an absolute position.

**Comment by kevinsimper** [comment]
@l-urence Yeah, I can see what you mean, but I think that is better than the current behaviour.

**Comment by l-urence** [comment]
@kevinsimper I will have a look at the weekend.

**Comment by l-urence** [comment]
@kevinsimper I prototyped a [fix](https://github.com/l-urence/react-native-autocomplete-input/commit/75170a8ff71c8fec45253ea8e6526bbb378feb90) for the absolute position. Can be installed via npm. Short feedback would be nice. Thx.

**Comment by kesha-antonov** [comment]
@l-urence Hello!
Just tested it. Looks good! 👍

**Comment by l-urence** [comment]
@kesha-antonov Great :). Will publish everything ASAP.

**Comment by tioback** [comment]
The fix didn't work for me in Android, but iOS works fine, as in images below.

![screen shot 2016-09-15 at 19 52 59](https://cloud.githubusercontent.com/assets/13951017/18570149/1f05b0e4-7b7e-11e6-9b84-df27a5f2ceb0.png)

![screen shot 2016-09-15 at 19 53 16](https://cloud.githubusercontent.com/assets/13951017/18570154/2827da3a-7b7e-11e6-8a4d-f226cc339e11.png)

**Comment by l-urence** [comment]
The android issues seems to be related to #20.

**Comment by tioback** [comment]
I managed to get it working with a [different approach](https://gist.github.com/tioback/6af21db0685cd3b1de28b84981f31cca). Thanks, anyway.

**Comment by l-urence** [comment]
@tioback Thanks for sharing you approach. Maybe I can integrate some of your ideas into the component.
