### ISSUE TITLE
Problem with list render

### ISSUE THREAD

**Issue by luisfuertes** [l-urence/react-native-autocomplete-input#17]
I have implemented the component, but the autocomplete list render fail.

My code: 
```
                <Autocomplete
                    data={subjects}
                    onChangeText={this.props.onChangeSearchTerm}
                    defaultValue={this.props.searchTerm}
                    autoCorrect={false}
                    ref = {'searchInput'}
                    style={{paddingLeft: 15, paddingRight: 15, color: Commons.Colors.black, fontFamily: Commons.Fonts.regular, fontSize: 16, textAlign: 'center', backgroundColor: Commons.Colors.white}}
                    inputContainerStyle={{borderWidth: 0}}
                    placeholder={'Buscar...'}
                    containerStyle={{}}
                    listStyle={{paddingRight: 15, paddingLeft: 15, backgroundColor: Commons.Colors.white}}
                    renderItem={value => (
                      <TouchableOpacity style={{justifyContent: 'center', backgroundColor: Commons.Colors.white}} onPress={() => {

                          this.refs.searchInput.blur();
           
                        }
                      }>
                        <Text style={{color: Commons.Colors.gray02, fontFamily: Commons.Fonts.regular, fontSize: 14}}>{value}</Text>
                      </TouchableOpacity>
                    )}
                  />
```

But the result: 
![captura de pantalla 2016-09-05 a las 8 46 10](https://cloud.githubusercontent.com/assets/18212615/18239593/85086534-7346-11e6-9f80-673dada03e8b.png)

Somebody know how can i fix it?

**Comment by l-urence** [comment]
Did you installed `v2.0.0-rc.0` and using `zIndex` on other components in your view then try to set a greater `zIndex` on autocomplete's `containerStyle` prop. Or use `v1.1.2` and set a absolute position on the autocomplete component like in the [example](https://github.com/l-urence/react-native-autocomplete-input/blob/master/example/Example.js#L93) from the master branch.


I accidentally published `v2.0.0-rc.0` on npm, but this might not be tested well enough - sorry.

**Comment by luisfuertes** [comment]
Oh, i use `v1.1.2` and works perfect.

Thanks!

**Comment by l-urence** [comment]
Cool then I will close this.
