### ISSUE TITLE
On press does not change the text input

### ISSUE THREAD

**Issue by Talkwondo** [l-urence/react-native-autocomplete-input#24]
Hi,
After the autocomplete find the element, when I select it this does not show in the text input. 
does anyone can understand what's happening?

<Autocomplete
             data={notEatitems.length === 1 && comp(query, notEatitems[0]) ? [] : notEatitems}
             defaultValue={query}
             keyboardShouldPersistTaps={true}
             onChangeText={text => this.setState({query: text})}
             renderItem={data => (
               <TouchableOpacity onPress={() =>
                   this.setState({query: data})}>
                 <Text style={{padding:5}}>{data}</Text>
               </TouchableOpacity>
             )}
            />

<img width="371" alt="screen shot 2016-11-06 at 12 51 35" src="https://cloud.githubusercontent.com/assets/20122139/20036948/cc68bac8-a41f-11e6-825d-0014882003bb.png">

**Comment by vasiliy-sarzhynskyi** [comment]
hi,

I also have the same issue as @Talkwondo described above. I tried in iOS and Android devices and result is the same. I also tried different versions of react-native-autocomplete-input (2.0.0 and 1.1.2) and still see the issue.
It seems that renderItem does not work at all, because alert is never invoked in the following example (similar as in Example.js):
renderItem={({ title, release_date }) => (
                        <TouchableOpacity
                            onPress={() => {
                                alert('onPress!')
                                this.setState({ query: title })
                            }}>
                            <Text style={styles.itemText}>
                                {title} ({release_date.split('-')[0]})
                            </Text>
                        </TouchableOpacity>
                    )}

any ideas?

**Comment by l-urence** [comment]
Strange.. Does it work with the example?

**Comment by vasiliy-sarzhynskyi** [comment]
unfortunately your example does not work for me (tried on real Android device and on iOS simulator)

**Comment by vasiliy-sarzhynskyi** [comment]
hi @l-urence,
I finally found root of my problem: I put autocomplete component inside ScrollView (already checked solution for #5).  So it works fine for Android and iOS with version 1.1.2.

As the title of issue: 'On press does not change the text input', I had the same behavior, but it could be solved by customizing component: use states for text input (defaultValue property) and key (autocompleteUpdateableKey: Math.random())

 <Autocomplete
                    // need this key for updating input field on selecting value from suggestion list
                    key={this.state.autocompleteUpdateableKey}
                    defaultValue={this.state.autocompleteDisplayedText}

**Comment by l-urence** [comment]
@vasiliy-sarzhynskyi cool then I will close this.
