### ISSUE TITLE
change autocomplete textbox background color.

### ISSUE THREAD

**Issue by aravindhrbt** [l-urence/react-native-autocomplete-input#27]
Hi @l-urence 
   I have used autocomplete input and my code looks like this
```
<Autocomplete
                    autoCapitalize="none"
                    autoCorrect={false}
                    containerStyle={{zIndex:5}}
                    inputContainerStyle={{borderColor:'transparent',height: 50,backgroundColor:'red'}}
                    data={countryList.length === 1 && comp(this.state.countryQuery, countryList[0].name) ? [] : countryList}
                    defaultValue={this.state.countryQuery}
                    onChangeText={text => this.setState({countryQuery: text })}
                    placeholder="Search for your country."
                    renderItem={data => (
                      <TouchableOpacity onPress={() => this.onCountrySelection(data)}>
                        <Text style={styles.itemText}>
                          {data.name}
                        </Text>
                      </TouchableOpacity>
                    )}
                    />
```
**I need is to change the background color to transparent so that it will look good with my design.**

i tried using background color in both containerStyle and inputContainerStyle but nothing works..

if use `style={{backgroundColor:'#ececec '}}` then it works for android not in iOS..

any workaround idea to get this done.

Thanks in advance.

**Comment by l-urence** [comment]
Try to use `backgroundColor: 'rgba(52, 52, 52, 0)'` instead of `borderColor:'transparent'`.

**Comment by aravindhrbt** [comment]
Thanks @l-urence 
here is the screenshot that i am using

![screen shot 2017-02-07 at 3 23 32 pm](https://cloud.githubusercontent.com/assets/16588358/22686314/a7993d9e-ed49-11e6-8a39-9184684363a3.png)
 for Search for your country. autocomplete
the prop that i used is
 ```
containerStyle={{zIndex:5}}
inputContainerStyle={{backgroundColor:'transparent'}}
```

for Search for your state.  autocomplete
the prop that i used is 
```
containerStyle={{zIndex:4}}
inputContainerStyle={{borderColor:'transparent'}}
```
for Search for your city.  autocomplete
the prop that i used is 
```
containerStyle={{zIndex:3}}
inputContainerStyle={{borderColor:'transparent'}}
```

**Comment by l-urence** [comment]
If you want to get rid of the border set it's width to zero: `inputContainerStyle={{ borderWidth: 0 }}`.

**Comment by aravindhrbt** [comment]
@l-urence 
i need to change the autocomplete textbox background color from white to the light grey(refer the previous image the  Search for your state. autocomplete should be light grey instead of white like confirm password textbox which is placed above the  Search for your state. autocomplete textbox) and remove the border too 

Removing border by using `inputContainerStyle={{ borderWidth: 0 }}` works 
**but i need to change the background color to light grey**

**Comment by l-urence** [comment]
If you want your autocomplete inputs like your *confirm password* text input try something like this:

```javascript
<Autocomplete
  style={{ backgroundColor: 'rgba(52, 52, 52, 0)', height: 50 }}
  inputContainerStyle={{ borderWidth: 0 }}
  // ...
/>
```

**Comment by aravindhrbt** [comment]
Thanks @l-urence 
It works. 
my working Code
```
 <Autocomplete
                      style={{ backgroundColor: '#ececec', height: 50,fontSize: 20 }}
                      inputContainerStyle={{ borderWidth: 0 }}
                      autoCapitalize="none"
                      autoCorrect={false}
                      containerStyle={{zIndex:3}}
                      data={renderCityList.length === 1 && renderCityListcomp(this.state.cityQuery, renderCityList[0]) ? [] : renderCityList}
                      defaultValue={this.state.cityQuery}
                      onChangeText={text => this.setState({cityQuery: text })}
                      placeholder="Search for your City"
                      renderItem={data => (
                        <TouchableOpacity onPress={() => this.onCitySelection(data)}>
                          <Text style={styles.itemText}>
                            {data}
                          </Text>
                        </TouchableOpacity>
                      )}
                      />
```

**I have one more question is it posible to show suggested result on top of text box?
 say for example, i have autocomplete text box at the bottom of the view when user types something  the suggested list populates at the top of textbox, so that it will be useful**.

**Comment by l-urence** [comment]
Sorry, right now the suggestion will only appear under the text box. If I find some time I may have a look at it. (PRs are welcome ;-))

**Comment by aravindhrbt** [comment]
Thanks a lot.... 🥇  @l-urence
