### ISSUE TITLE
Forcing renderItem to run on any Keypress

### ISSUE THREAD

**Issue by Akshay9882** [l-urence/react-native-autocomplete-input#28]
The data is loaded only on first keypress and backspace in the autocomplete and for all further keypresses  the data is only filtered. 

Thus renderItem runs only during first keypress or when backspacekey is pressed.

I have written my autocompete suggestion logic inside renderItem so i need it to run every time a key is pressed. Is it possible?

Depending on the suggestions loaded further more 5 rows are loaded which are dependent on suggestions.I am trying to build country suggestion and its top 5 tourist attractions places.

For example if some one types "ind" autocomplete suggestion would show india as first suggestion and then more 5 rows are displayed. These 5 rows shows top 5 tourist attractions in india.

I have written my logic in renderItem, so I need it to run on any keypress
` renderItem={({ country, touristlist_array }) => { if(dataset.length>0) { this.loadResults(touristlist_array); if(some condition){ return (<View> <TouchableOpacity onPress={() => this.setState({ query: country })}> <Text style={styles.itemText}> {country} </Text> </TouchableOpacity> {this.load_topfive_touristattractions()} //loads another 5 rows </View> );} else { return (<TouchableOpacity onPress={() => this.setState({ query: country })}> <Text style={styles.itemText}> {title} </Text> </TouchableOpacity>); } }}}`

**Comment by l-urence** [comment]
Did you try to put your logic inside `onChangeText` and use some state for your conditions? `onChangeText` will get fired every time the text changes in the text input.

**Comment by Akshay9882** [comment]
Shall i paste the same renderItem code over there or add some extra code?

**Comment by l-urence** [comment]
Just copy and paste isn't going to do the job. What you need to to is to pass a different set of data to the autocomplete this will trigger the `renderItem` function. The easiest way to do this is to set your filter query with `onChangeText`. Have a look at the example maybe this will give you an idea.

**Comment by Akshay9882** [comment]
Is there any other way to call it programatically?

**Comment by Akshay9882** [comment]
`        onChangeText={text => this.setState({ query: text,flag:0,topPackages:[],locations_count:0,topPackages_Index:0,locations:[]})}` Its working i reset the location array to empty to forcefully call it

**Comment by l-urence** [comment]
Cool beans! Btw there is no way to call it programmatically. An alternative you can try is to use [forceupdate()](https://facebook.github.io/react/docs/react-component.html#forceupdate) if you have a `ref` to the autocomplete (not tested).

**Comment by Akshay9882** [comment]
Thanks a lot.
