### ISSUE TITLE
Example request: autocomplete for country phone code 

### ISSUE THREAD

**Issue by karthickvkumar** [l-urence/react-native-autocomplete-input#3]
Hi @l-urence, Thank you for this awesome library. I'm new to react native it would be more helpful if you provide an eample of autocomplete for country phone code picker. 

Thanks in Advance

**Comment by l-urence** [comment]
Can you give me a more detailed description how this should look like (maybe an image). Then I try to add an example by the weekend.

**Comment by karthickvkumar** [comment]
Hi @l-urence, Thank you so much for your quick response. I herewith attached an image, how that country calling code autocomplete looks like
![screenshot_2013-12-28-14-11-43](https://cloud.githubusercontent.com/assets/11032434/14731429/1748af2e-086e-11e6-8353-3846bab06007.png)

Thanks in Advance

**Comment by l-urence** [comment]
I started an example under the [country-phone-code](https://github.com/l-urence/react-native-autocomplete-input/tree/country-phone-code) branch. It's not complete right now, but you may find some ideas for your implementation.

**Comment by karthickvkumar** [comment]
@l-urence  Thank you very much
