### ISSUE TITLE
Set scroller to suggestions container

### ISSUE THREAD

**Issue by kamleshchandnani** [l-urence/react-native-autocomplete-input#31]
I am setting `listContainerStyle={{ height: 300 }} `It works even I am able to see the scroller but I cannot scroll. When I try to scroll then scrollview gets scrolled.

**Comment by l-urence** [comment]
Did you try to set `keyboardShouldPersistTaps={true}` on your scroll view?

**Comment by l-urence** [comment]
I will close this for now because of no further interaction.
