### ISSUE TITLE
Text input background color

### ISSUE THREAD

**Issue by magesuko** [l-urence/react-native-autocomplete-input#34]
![input](https://cloud.githubusercontent.com/assets/3919468/24326207/7a90a5a4-11ba-11e7-8297-65a2d5359e5c.jpg)

Hello, I want to change the background color of the text input and also the radius but, as you can see the image, giving "inputContainerStyle" a style doesnt seem to be working? What am I doing wrong?

thanks.

**Comment by l-urence** [comment]
Try to use:

```javascript
<Autocomplet style={{ backgroundColor: 'black' }} />
```

**Comment by magesuko** [comment]
Thank you it worked :) Not I need to put seach icon inside text input. Is it possible? And I want to get rid of this grey border but dont know how.  And I also want to change the color of the placeholder.
![screen shot 2017-03-27 at 23 51 44](https://cloud.githubusercontent.com/assets/3919468/24377580/800566e8-1348-11e7-84d5-fc71fdfa7925.png)

**Comment by l-urence** [comment]
Try to set `<Autocomplete listStyle={{ borderWidth: 0 }}/>`

**Comment by magesuko** [comment]
Thanks again. 

I just need to do two more thing here.

1- How can I put a search icon inside the text box?
2- How can I set placeholder text color?

Thank you.

**Comment by l-urence** [comment]
You can set the placeholder color with `placeholderTextColor`.

To get a search icon next to your input try something like this:

```javascript
<View style={{ flexDirection: "row", borderWidth: 1 }}>
  <View>
    <Autocomplete
      style={styles.autocomplete}
      inputContainerStyle={{ borderWidth: 0 }}
      listStyle={{ borderWidth: 1 }}
    />
 </View>
 <Text>?</Text>
</View>
```
(I tried this only in the iOS-Simulator.)

or try to render your input element with `renderTextInput`, which accepts a function returning your custom input.

**Comment by jlf123** [comment]
@magesuko could you share all the styles you used to get the rounded input?

**Comment by rabin111** [comment]
@magesuko Your sharing is much appreciate. Please share us how to make a rounded textinput. Thank you!!

**Comment by interose** [comment]
@jlf123 @rabin111 
Hi, it's pretty late but I was also looking for a solution for styling the text input. Here is my solution. It's only tested on IOS simulator but maybe it helps:

![bildschirmfoto 2018-02-06 um 10 39 10](https://user-images.githubusercontent.com/3026784/35852051-1a9c6d58-0b2a-11e8-859a-bb3cb032fb02.png)

```javascript
<Autocomplete
    style={{backgroundColor: '#fff', padding: 10, borderRadius: 16}}
    inputContainerStyle={{backgroundColor: '#c6c6c6', padding: 13}}
    containerStyle={{}}
```
