### ISSUE TITLE
Failed prop type: Invalid prop `keyboardShouldPersistTaps` of type `string` supplied to `ListView`, expected `boolean`

### ISSUE THREAD

**Issue by peacechen** [l-urence/react-native-autocomplete-input#41]
The prop `keyboardShouldPersistTaps` changed from a bool in RN <= 0.39 to a string enum in RN > 0.40.  Setting the prop to a string inside react-native-autocomplete-input breaks RN <= 0.39.  Since the type change is a breaking change, it would be better to let the caller of this library set the prop and pass it on the ListView.

**Comment by tiaaaa123** [comment]
@peacechen The modification you made does not work, because `View.propTypes` does not have `keyboardShouldPersistTaps`. ScrollView does!
index.js, line 36
```
keyboardShouldPersistTaps: ScrollView.propTypes.keyboardShouldPersistTaps

// instead of 

keyboardShouldPersistTaps: View.propTypes.keyboardShouldPersistTaps,
```

Your fix only change the error for : `prop type `keyboardShouldPersistTaps` is invalid; it must be a function, usually from React.PropTypes.`

**Comment by l-urence** [comment]
Fixed by #48.

**Comment by peacechen** [comment]
@tiaaaa123  I believe the bug was introduced during the refactor merge.  My original PR didn't use  PropTypes, though it's good practice to do it.

Note that there's a breaking change in React Native 0.45 (specifically React 16.x) regarding prop types.  They've moved PropTypes out of core React and into a separate package that needs to be added as a dependency.
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by l-urence** [comment]
@peacechen There are already PRs for that (#46 and #47). Not quite sure how to handle them because they will break the component with older RN versions.

**Comment by peacechen** [comment]
Since `prop-types` is now a separate package, does it work stand-alone with previous versions of React?  Just don't use the React.PropTypes class, replace it with PropTypes from the `prop-types` library.

The other changes (ViewPropTypes instead of View.PropTypes) are more problematic.  Wonder if there's a way for all of those to use the `prop-types` library.
