### ISSUE TITLE
Item's onPress does not work when inside ScrollView

### ISSUE THREAD

**Issue by joonhocho** [l-urence/react-native-autocomplete-input#5]
As title says, selecting item is not working when nested inside a ScrollView.

**Comment by joonhocho** [comment]
Related https://github.com/facebook/react-native/issues/7572

**Comment by l-urence** [comment]
Do you have still problems with RN v0.26.2?

**Comment by saemie** [comment]
I am getting the same problem with RN v0.26.2
onPress does not work for items passed to the renderItem property.

I'm testing this with the example app. Any idea what the problem may be?

**Comment by l-urence** [comment]
@saemie Do you use the same code from the example? Do you test on the device or emulator?

**Comment by ajoshdee** [comment]
Hi, I tested it using your example but I'm having a hard time selecting from the list returned by autocomplete. my autocomplete component is inside a scroll view

**Comment by ajoshdee** [comment]
The items doesn't seem to be in a list, i can't scroll through it.

**Comment by bbalu** [comment]
After removing this following line, TouchOpactity onPress function is being called.
<TextInput
...
onEndEditing={e =>
      this._showResults(false) || (onEndEditing && onEndEditing(e))
}
...

**Comment by ltquang** [comment]
Hello sir,
I have 1 solution for you
please add `keyboardShouldPersistTaps={true}` in your scrollview
<ScrollView keyboardShouldPersistTaps={true}>
.
.
.
   <Autocomplete
                    data={data}
                    onChangeText={this.props.onSelectedProvinceChange}
                        defaultValue={this.props.province}
                        autoCorrect={false}
                        style={{paddingLeft: 15, paddingRight: 15, color: Commons.Colors.gray_dark, fontFamily: Commons.Fonts.regular, fontSize: Commons.Fonts.p,}}
                        inputContainerStyle={{borderRadius: 4, borderColor: Commons.Colors.gray}}
                        containerStyle={{marginRight: 5, marginLeft: 5}}

                    renderItem={data => (
                      <TouchableOpacity onPress={() => this.props.onSelectedProvinceChange(data)}>
                        <Text style={{color: Commons.Colors.gray_dark, fontFamily: Commons.Fonts.regular, fontSize: Commons.Fonts.p}}>{data}</Text>
                      </TouchableOpacity>
                    )}
                  />
</ScrollView>
*It's work for me :) Hope to help you

**Comment by l-urence** [comment]
Thx @ltquang your  suggestion to add the `keyboardShouldPersistTaps={true}` prop to the `ScrollView` seems to fix the issue.

**Comment by panuhorsmalahti** [comment]
While adding keyboardShouldPersistTaps to true (well, "always" these days) fixes this issue, I need to have keyboardShouldPersistTaps "never" to close the keyboard after clicking outside inputs.

**Comment by armadillojim** [comment]
@panuhorsmalahti, have you tried setting `keyboardShouldPersistTaps` to `handled`?  Dunno if that'll fix your issue, but it's worth a try.  FWIW, I have a `ScrollView` with multiple autocomplete fields, and clicking outside them closes the keyboard for me.

**Comment by c-goettert** [comment]
@armadillojim  'handled' works great on android, but on iOS the autocomplete scroll still behaves buggy. Although in principle you can select elements and close the autocomplete window by tapped outside the range, the autocomplete view often closes randomly when scrolling inside the autocomplete-view.

**Comment by c-goettert** [comment]
@panuhorsmalahti I managed to get it working with `keyboardShouldPersistTaps='always'` and [Naomipols solution](https://github.com/mrlaessig/react-native-autocomplete-input/issues/57#issuecomment-332723713) for nested ScrollView from another thread.
To automatically dismiss the keyboard again (if the user taps outside the list), I just use `componentDidUpdate` of the Parent View, e.g. like this:
```
  componentDidUpdate (prevProps, prevState) {
    const previouslyEnabled = prevState.enableScrollViewScroll
    const newEnabled = this.state.enableScrollViewScroll
    // if scroll was just enabled again, that means user tapped outside of autocomplete list
    // -> manually dismiss keyboard then, because we set keyboardShouldPersistTaps to 'always'
    if (previouslyEnabled !== newEnabled && newEnabled) {
      Keyboard.dismiss()
    }
  }
```

**Comment by gauravgandhigg** [comment]
Hi 

> Hello,
> I have 1 solution for you
> please add `keyboardShouldPersistTaps={true}` in your scrollview
> 
> ```
> ScrollView keyboardShouldPersistTaps={true}
> .
>    Autocomplete
>                     ....
>                     renderItem={data => (
>                       <TouchableOpacity onPress={() => this.props.onSelectedProvinceChange(data)}>
>                         <Text style={{color: Commons.Colors.gray_dark, fontFamily: Commons.Fonts.regular, fontSize: Commons.Fonts.p}}>{data}</Text>
>                       </TouchableOpacity>
>                     )}
>                   />
> /ScrollView
> ```
> 
> *It's work for me :) Hope to help you

Hey So this solution also works when we use a picker inside a scrollview. Thank you.
