### ISSUE TITLE
Trouble changing the results font.

### ISSUE THREAD

**Issue by johngoren** [l-urence/react-native-autocomplete-input#53]
This module is great but wondering if it's possible to change the font of the results list. I tried to pass in fontSize to props.listStyle but was told it was not supported.

**Comment by huy-lv** [comment]
You should put it in renderItem:
renderItem={data => (
      <TouchableOpacity onPress={() => this.setState({ query: data })}>
        <Text style={{**fontSize**:20}}>{data}</Text>
      </TouchableOpacity>
    )}

**Comment by johngoren** [comment]
Thanks! That helps a lot.
