### ISSUE TITLE
Migrate to prop-types package (React.PropTypes has been deprecated)

### ISSUE THREAD

**Issue by peacechen** [l-urence/react-native-autocomplete-input#54]
React 16 (the default version for RN 0.45) has deprecated React.PropTypes.  The package `prop-types` should be used instead.
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Console log react-native-autocomplete-input/index.js line 18:
`ExceptionsManager.js:71 Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.`

All other PropTypes should use the prop-types package as well.  Remove PropTypes from
`import React, { Component, PropTypes } from 'react';`
and add
`import PropTypes from 'prop-types';`

**Comment by peacechen** [comment]
PR #55 addresses the React.PropTypes and View.propTypes deprecations.

The merge of @kesha-antonov's PR overwrote @Dmytro Gorelik's fix for the `keyboardShouldPersistTaps` prop.  This PR restores that since it needs to support both bool and string types.

**Comment by dmytro** [comment]
@peacechen Different Dmytro. Gorelik is @dhorelik

**Comment by peacechen** [comment]
Sorry about that. Github automatically linked to you instead of gorelik.

**Comment by l-urence** [comment]
Closed because of #55.

**Comment by ericmager** [comment]
It seems this has come up again but slightly different. Here's a console warning 

`ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.`

`at node_modules/react-native-autocomplete-input/index.js:85:38 in <global>`
