### ISSUE TITLE
Need some help on styling text input.

### ISSUE THREAD

**Issue by hareendras** [l-urence/react-native-autocomplete-input#59]
Hi,
Can you please provide an example code for applying custom style to auto complete text input? I'm trying to use renderTextInput method as follows.
```
 renderTextInput(props) {
   const myProps = {
     style: [styles.textInp, ...props.style],
     ...props
   };   
   return <TextInput {...myProps} />;
 }

```

**Comment by hareendras** [comment]
I used <Autocomplete style={styles.textInp} /> and it works. Just saw the soulution in #34

**Comment by ryanwebjackson** [comment]
> I used `<Autocomplete style={styles.textInp} />` and it works. Just saw the solution in #34

Do you have an example of the styles that worked for you? I didn't see 'styles.textInp' in the referenced issue.
