### ISSUE TITLE
Two clicks needed to select the item from the list

### ISSUE THREAD

**Issue by mtimofiiv** [l-urence/react-native-autocomplete-input#63]
Here is my component:

```jsx
          <Autocomplete
            data={possibleAddresses}
            inputContainerStyle={styles.inputElement}
            style={styles.inputBox}
            containerStyle={styles.autocompleteContainer}
            placeholder="321 Acme St"
            onChangeText={text => this.lookupAddressMatches(text)}
            listStyle={styles.resultList}
            renderItem={data => (
              <TouchableOpacity
                onPress={() => this.setAddress(data)}
              >
                <Text style={styles.resultListItem}>{data.formattedAddress}</Text>
              </TouchableOpacity>
            )}
          />
```

My problem is that in order to select an item from the list, they have to click twice on it (at least on Android, haven't tried ios).

The first click blurs the input box and the second click triggers the `onPress` of the `TouchableOpacity` in my `renderItem`.

Is there a way to not have this behaviour and have the `onPress` callback triggered even if the field is not currently blurred?

**Comment by ilove8** [comment]
same on iOS

**Comment by ilove8** [comment]
You can use ScrollView with `keyboardShouldPersistTaps='always'`. it worked!

**Comment by abhisri2090** [comment]
@ilove8 hey can please tell me exactly how and where to use ScrollView and keyboardShouldPersistTaps='always', i still have the same problem,

on the first click, on an option, keyboard is closed and then on second click that option is being selected


> 
                <View>
                ...
                <ScrollView style={styles.autocompleteContainer}>
                    <Autocomplete
                        autoCapitalize="none"
                        keyboardShouldPersistTaps='always'
                        placeholder='enter your skills'
                        autoCorrect={false}
                        containerStyle={styles.autocompleteContainer}
                        data={(skillsData.length === 1 && compare(skillsData[0], this.state.qSkill) ? [] : skillsData)}
                        onChangeText={(value) => this.setState({ qSkill: value })}   //for input box
                        defaultValue={this.state.qSkill}   //for input box same as value
                        renderItem={(skillsData) => (
                                <TouchableOpacity onPress={() => {
                                    var tempSelectedSkills = this.state.selectedSkills
                                    tempSelectedSkills.push(skillsData)
                                    this.setState({ selectedSkills: tempSelectedSkills, qSkill: '' })
                                }} >
                                    <Text style={styles.itemText}>
                                        {skillsData}
                                    </Text>
                                </TouchableOpacity>
                        )}
                    />
                </ScrollView>
                ...
                </View>

**Comment by ilove8** [comment]
@abhisri2090 I couldn't remember exactly, but you should try `keyboardShouldPersistTaps='always' on <ScrollView>

```
<ScrollView style={styles.container} keyboardDismissMode='on-drag' keyboardShouldPersistTaps='always'>
...
</ScrollView>

**Comment by abhisri2090** [comment]
@ilove8 thnaks for reply, but it didn't work for me...
although, when I first press back button to hide keyboard and then when I press on the options, it is being selected in one press only.

**Comment by KrisGerhard** [comment]
There is an open merge-request for react-native to fix this issue on Android. This should fix the workaround :)
https://github.com/facebook/react-native/pull/26422
