### ISSUE TITLE
dynamic list style

### ISSUE THREAD

**Issue by vvavepacket** [l-urence/react-native-autocomplete-input#68]
lets say, we have 1000 items on the list,, therefore, setting the liststyle like this

`listStyle={{height: 100}}`

will make sure your dropdown will be limited to the height. However, if the list contains fewer items like 1 or 2, the dropdown will still show greater height. how do we make it dynamic in the sense if items are too much, then fixed the height,, then if not, then adjust the height accordingly?

**Comment by AmyNgithub** [comment]
Hi @vvavepacket! I had the same question and I think I have found a solution. 
I used this example: https://github.com/l-urence/react-native-autocomplete-input/blob/master/example/Example.ios.js 

Then I modified/added the last three lines in findFilm:

```
  findFilm(query) {
    if (query === '') {
      return [];
    }

    const { films } = this.state;
    const regex = new RegExp(`${query.trim()}`, 'i');
    const results = films.filter(film => film.title.search(regex) >= 0);
    const size = 10; // Where size is the maximum number of results you want to display
    return results.slice(0, size);
  }
```

**Comment by l-urence** [comment]
Thx @AmyNgithub for posting your solution.
