### ISSUE TITLE
onShowResult not working in android

### ISSUE THREAD

**Issue by naveenvignesh5** [l-urence/react-native-autocomplete-input#79]
onShowResult is not triggered after result list is being rendered.

`<Autocomplete 
 ...
onShowResult={() => console.log('onShowResult triggered')}
...
/>
`

**Comment by naveenvignesh5** [comment]
I gave console.log() directly inside braces and it works.

**Comment by AkshayBaldia** [comment]
@naveenvignesh5 If I try to use console.log() directly inside braces function runs automatically on activity start.
